version: '3'

services:
  icbc-bot:
    build: .
    container_name: icbc-appointment-bot
    environment:
      - NODE_ENV=production
      # Email notification settings - replace with your actual email
      # To get an app-specific password for Gmail:
      # 1. Go to https://myaccount.google.com/ > Security
      # 2. Under "Signing in to Google", select "App passwords" (requires 2-Step Verification)
      # Gmail no longer supports app passwords for most accounts.
      # You must enable "Less secure app access" (not recommended), or use an email provider that supports SMTP with username/password.
      # Alternatively, set up an "App Password" if your Google Workspace admin allows it, or use a service-specific password from another provider.
      # For Gmail, you may need to use OAuth2 authentication instead of a password.
      # See: https://nodemailer.com/usage/using-gmail/ for more info.
      - NOTIFICATION_EMAIL=auggieldoggie@gmail.com
      - GMAIL_USER=auggieldoggie@gmail.com
      - GMAIL_APP_PASSWORD=your_app_specific_password_here
    volumes:
      # Use config.js now that we've copied the file
      - ./src/config.js:/usr/src/app/src/config.js
      # Mount a volume for persistent browser data
      - browser-data:/home/appuser/.cache
    restart: unless-stopped
    # Puppeteer needs these capabilities to run in Docker
    cap_add:
      - SYS_ADMIN
    # Use host network to avoid proxy issues
    network_mode: host

volumes:
  browser-data: 